// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAZ1ZHeNgIfc9UtMBO3F007GYtcMKsyfw',
    appId: '1:142197621968:web:c123c7f13bbd276ac60ad5',
    messagingSenderId: '142197621968',
    projectId: 'cw12-78b5d',
    authDomain: 'cw12-78b5d.firebaseapp.com',
    storageBucket: 'cw12-78b5d.firebasestorage.app',
    measurementId: 'G-WC8XPXP4RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB13aCF1xfSKACh6XNFo5kxzpDVVWIHhq0',
    appId: '1:142197621968:android:bf839246ba068d9dc60ad5',
    messagingSenderId: '142197621968',
    projectId: 'cw12-78b5d',
    storageBucket: 'cw12-78b5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9C8Ldwtf7HUXC7hZ9Evl-DC3tt_BmAr8',
    appId: '1:142197621968:ios:80f27e832c28c0b0c60ad5',
    messagingSenderId: '142197621968',
    projectId: 'cw12-78b5d',
    storageBucket: 'cw12-78b5d.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9C8Ldwtf7HUXC7hZ9Evl-DC3tt_BmAr8',
    appId: '1:142197621968:ios:80f27e832c28c0b0c60ad5',
    messagingSenderId: '142197621968',
    projectId: 'cw12-78b5d',
    storageBucket: 'cw12-78b5d.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAZ1ZHeNgIfc9UtMBO3F007GYtcMKsyfw',
    appId: '1:142197621968:web:218bdfa1cd8c2c53c60ad5',
    messagingSenderId: '142197621968',
    projectId: 'cw12-78b5d',
    authDomain: 'cw12-78b5d.firebaseapp.com',
    storageBucket: 'cw12-78b5d.firebasestorage.app',
    measurementId: 'G-P223RWSB4R',
  );
}
